name: Ejecutar Scraper Carrefour

on:
  schedule:
    - cron: "0 12 * * *"  # todos los días a las 12 UTC
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4 pandas matplotlib

      - name: Ejecutar scraper
        run: python scraper/carrefour.py

      - name: Commit y push
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "GitHub Actions Bot"
          git add .
          git commit -m "Actualización diaria automática" || echo "No hay cambios"
          git push

